Updated with shorter senteces, & more coherent wording
fixed some of the danish language, as a user of filepond these have annoyed me for a while because of a couple of reasons..
1. sentences was longer then necessary,
2. mixed format of how messages was written where it should follow a standard to have a better readability, like an format of - Action, Reaction, e.g.

previously:
    labelFileProcessingAborted: 'Upload(action) annulleret(Reaction)',
    labelFileProcessingError: 'Fejl(Reaction) under upload(action) ',

now:
    labelFileProcessingAborted: 'Upload(Action) annulleret(Reaction)',
    labelFileProcessingError: 'Upload(Action) fejlede(Reaction)',

did this in a couple of places where it was needed, that also cut down sentence lengths.
finally i fixed a few translating erros, e.g "Loading" is still English, whereas "Loader" would be the Danish word.